logging:
  level:
    sql: info
    root: info
    web: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
#    'liquibase':info
spring:
  datasource:
    url: jdbc:postgresql://localhost:5439/cinema_db
    username: cinema_user
    password: cinema_password


  jpa:
    show-sql: true
    open-in-view: false

    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: on
        highlight_sql: on
        use_sql_comments: off
        generate_statistics: on

  #  test:
  #    database:
  #      replace: none

  liquibase:
    change-log: db/changelog/changelog-master.yml
    url: jdbc:postgresql://localhost:5439/cinema_db
    user: cinema_user
    password: cinema_password
