--liquibase formatted sql
--changeset A.Yefriemov:create-movie

create table if not exists movie
(
    id            bigint generated by default as identity
        constraint movie_pk primary key,
    version       bigint    default 0     not null,
    created_date  timestamp default now() not null,
    modified_date timestamp default now() not null,
    title         varchar(20)             not null,
    timing        smallint
        constraint timing_not_positive CHECK ( timing > 0 ),
    producer      varchar(20)             not null
);
create index if not exists movie_title on movie (title);