--liquibase formatted sql
--changeset A.Yefriemov:create_movie_hall

create table if not exists cinema_hall
(
    id            bigint generated by default as identity
        constraint cinema_hall_pk primary key,
    version       bigint    default 0     not null,
    created_date  timestamp default now() not null,
    modified_date timestamp default now() not null,
    name          varchar(20)             not null
        constraint cinema_hall_name_not_unique unique,
    seats_amount  smallint                not null
        constraint seats_amount_not_positive check ( seats_amount > 0 ),
    seats_type    jsonb     default '{}'  not null

)