--liquibase formatted sql
--changeset A.Yefriemov:create-time_table

create table if not exists time_table
(
    id             bigint generated by default as identity
        constraint time_table_pk primary key,
    version        bigint    default 0     not null,
    created_date   timestamp default now() not null,
    modified_date  timestamp default now() not null,
    movie_id       bigint                  not null
        constraint time_table_movie_fk references movie,
    cinema_hall_id bigint                  not null
        constraint time_table_cinema_hall_fk references cinema_hall,
    start_session  timestamp               not null,
    base_price     smallint                not null,
    closed_seats   jsonb     default '{}'  not null,
    sold           boolean   default false
);
create index if not exists time_table_movie_id on movie (id);
create index if not exists time_table_cinema_hall_id on cinema_hall (id);
create index if not exists time_table_start_session on time_table (start_session);
create index if not exists time_table_sold on time_table (sold);
