--liquibase formatted sql
--changeset A.Yefriemov:create_order

create table if not exists order_table
(
    id            bigint generated by default as identity
        constraint order_table_pk primary key,
    version       bigint    default 0     not null,
    created_date  timestamp default now() not null,
    modified_date timestamp default now() not null,
    time_table_id bigint                  not null
        constraint order_table_time_table_fk references time_table,
    order_price   bigint                  not null
        constraint order_table_order_price_negative check ( order_price >= 0 ),
    seats         jsonb     default '{}'  not null,
    customer      varchar(50)
);
create index if not exists order_table_time_table on order_table (time_table_id);
create index if not exists order_table_price on order_table (order_price);